name: Build & Deploy to Netcup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: App bauen
        run: npm run build

      - name: lftp installieren
        run: sudo apt-get install -y lftp

      - name: Zum Netcup Server hochladen
        run: |
          lftp -e "
            set ftp:ssl-allow yes;
            set ssl:verify-certificate yes;
            open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
            mirror -R --delete ./dist/ ${{ secrets.FTP_SERVER_DIR }};
            quit
          "
